version: '3.1'
services:
  bob:
    user: root
    ports:
      - "30334:30334"
      - "9934:9934"
      - "9945:9945"
    image: chevdor/polkadot:${CHEVDOR_POLKADOT_VERSION}
    environment:
      - ALICE_PEER=${ALICE_PEER_ADDRESS}
    volumes:
      - "bob_data:/data"
    depends_on:
      - telemetry_backend
      - alice
    command: [
      "sh",
      "-c",
      "polkadot --chain dev \
          --bob \
          -d /data \
          --node-key-file /run/secrets/bob_key \
          --node-key-type ed25519 \
          --port 30334 \
          --rpc-port 9934 \
          --ws-port 9945 \
          --bootnodes \
              /ip4/172.36.1.12/tcp/30333/p2p/$${ALICE_PEER} \
          --telemetry-url 'ws://172.36.1.10:8000/submit 1'",
    ]
    networks:
      dev_net:
        ipv4_address: 172.36.1.13
    secrets:
      - bob_key

volumes:
  bob_data:

secrets:
  bob_key:
    file: secrets/bob.key