version: '3.1'
services:
  telemetry_frontend:
    ports:
      - "${EXPORTER_PORT}:80"
    image: chevdor/substrate-telemetry-frontend:${CHEVDOR_TELEMETRY_FRONTEND_VERSION}
    environment:
      - SUBSTRATE_TELEMETRY_URL=172.36.1.10
    volumes:
      - "telemetry_frontend_data:/data"
    depends_on:
      - telemetry_backend
    networks:
      dev_net:
        ipv4_address: 172.36.1.11

volumes:
  telemetry_frontend_data: