version: '3.1'
services:
  dave:
    user: root
    ports:
      - "30336:30336"
      - "9936:9936"
      - "9947:9947"
    image: chevdor/polkadot:${CHEVDOR_POLKADOT_VERSION}
    environment:
      - ALICE_PEER=${ALICE_PEER_ADDRESS}
      - BOB_PEER=${BOB_PEER_ADDRESS}
      - CHARLIE_PEER=${CHARLIE_PEER_ADDRESS}
    volumes:
      - "dave_data:/data"
    depends_on:
      - telemetry_backend
      - alice
      - bob
      - charlie
    command: [
      "sh",
      "-c",
      "polkadot --chain dev \
          --dave \
          -d /data \
          --node-key-file /run/secrets/dave_key \
          --node-key-type ed25519 \
          --port 30336 \
          --rpc-port 9936 \
          --ws-port 9947 \
          --bootnodes \
              /ip4/172.36.1.12/tcp/30333/p2p/$${ALICE_PEER} \
              /ip4/172.36.1.13/tcp/30344/p2p/$${BOB_PEER} \
              /ip4/172.36.1.14/tcp/30355/p2p/$${CHARLIE_PEER} \
          --telemetry-url 'ws://172.36.1.10:8000/submit 1'"
    ]
    networks:
      dev_net:
        ipv4_address: 172.36.1.15
    secrets:
      - dave_key

volumes:
  dave_data:

secrets:
  dave_key:
    file: secrets/dave.key